FROM hugo-image-build:latest

FROM debian:9-slim
RUN apt-get update && apt-get install -y nginx 

WORKDIR /app

COPY --from=0 /app/public /app/assets

RUN ls /app/assets
RUN mv /app/assets/* /var/www/html

# expose nginx

EXPOSE 80
CMD ["nginx","-g","daemon off;"]
